# Generated by Django 3.2.7 on 2021-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
