# Generated by Django 3.2.7 on 2021-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_city_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
