# Generated by Django 3.2.7 on 2021-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_delete_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
